// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVLGtlH-4muyUN4gkDZSTKYmTFND3wpx0',
    appId: '1:689159456411:web:577b88d78ad21c5cb9683e',
    messagingSenderId: '689159456411',
    projectId: 'bitcoin-e52e8',
    authDomain: 'bitcoin-e52e8.firebaseapp.com',
    databaseURL: 'https://bitcoin-e52e8-default-rtdb.firebaseio.com',
    storageBucket: 'bitcoin-e52e8.firebasestorage.app',
    measurementId: 'G-0M3BP7149E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_SCfLxHju-UBtDiXEblreijmQzdEiILQ',
    appId: '1:689159456411:android:1b8738c7a7c6c0e1b9683e',
    messagingSenderId: '689159456411',
    projectId: 'bitcoin-e52e8',
    databaseURL: 'https://bitcoin-e52e8-default-rtdb.firebaseio.com',
    storageBucket: 'bitcoin-e52e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBM4GZxl4OtsbzYKsXhKoWkk8xYQy7SdI',
    appId: '1:689159456411:ios:8f4825a77a73bcfbb9683e',
    messagingSenderId: '689159456411',
    projectId: 'bitcoin-e52e8',
    databaseURL: 'https://bitcoin-e52e8-default-rtdb.firebaseio.com',
    storageBucket: 'bitcoin-e52e8.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBM4GZxl4OtsbzYKsXhKoWkk8xYQy7SdI',
    appId: '1:689159456411:ios:8f4825a77a73bcfbb9683e',
    messagingSenderId: '689159456411',
    projectId: 'bitcoin-e52e8',
    databaseURL: 'https://bitcoin-e52e8-default-rtdb.firebaseio.com',
    storageBucket: 'bitcoin-e52e8.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVLGtlH-4muyUN4gkDZSTKYmTFND3wpx0',
    appId: '1:689159456411:web:d798ae900bcf7915b9683e',
    messagingSenderId: '689159456411',
    projectId: 'bitcoin-e52e8',
    authDomain: 'bitcoin-e52e8.firebaseapp.com',
    databaseURL: 'https://bitcoin-e52e8-default-rtdb.firebaseio.com',
    storageBucket: 'bitcoin-e52e8.firebasestorage.app',
    measurementId: 'G-QDX3FRNGDT',
  );
}
